/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is auto-generated by `next dev` / `next build`. Do not edit it by
// hand — it's included here only so the project type-checks before your first build.
